### ISSUE TITLE
Tracking issue for all links and placeholder docs in our GA site.

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc.github.io#258]
Main page:
- [x]  Works Across All platforms and Start quickly and scale both lead to quickstarts. @zinuga 
- [x]  Bi-directional streaming and auth does not lead anywhere. @zinuga 
- [x] Get started at bottom of page does not lead anywhere. @zinuga  
- [x]  Quickstarts at bottom of page need to be populated.  @zinuga 
- [x] Community link at bottom of page links to github.com/grpc/grpc.github.io , whereas fork me on github leads to github.com/grpc/grpc @zinuga to change this to ``github.com/grpc/grpc```

About page:
- [x] Presentation and Talks on 'About page' are placeholders to non gRPC content. 
- [x] "For more background on why we created gRPC, read the gRPC Motivation & Design Principles blog" This leads back to the about page, needs to be referenced to the right blog post. Also, the linked text is not bolded. @zinuga

Docs page:
- [x] _All_ links in the docs page just point back to itself and need to be updated. 

Quickstarts page:
- [x] Currently the main page text is just a placeholder, this needs to be updated with the right content.. @hsaliak

Blog page
- [x] Subscribe to blog goes nowhere, we need to update this.  @zinuga Needs to connect to mailchimp account. 

Community page
- [x] The "or shortcut to.." links are not correctly set. @ejona86
- [x] Join the mailing list opens up an email to the mailing list, it should direct to the correct [google groups link](https://groups.google.com/forum/#!forum/grpc-io) @ejona86

**Comment by hsaliak** [comment]
@zinuga can you clarify where some of the missing links should point to?
Please also look at the docs page, especially the parts about "gRPC by use cases"

**Comment by zinuga** [comment]
Have a PR in to fix a lot of the homepage and about page issues
https://github.com/grpc/grpc.github.io/pull/268

More to follow in a separate PR.

**Comment by hsaliak** [comment]
Thanks Varun, PR looks good, can you also check off some of the issues this addresses after I merge it in?

**Comment by ejona86** [comment]
- [ ] list item text should be lighter (it is too dark), to match surrounding paragraphs

**Comment by hsaliak** [comment]
- [ ] Bullets points on the new site look awkward, I think there is unnecessary stylistic variation which gives it an inconsistent feel. Example screenshot:

![image](https://cloud.githubusercontent.com/assets/150108/17319327/d11c711a-5841-11e6-9a9a-faba63bc643f.png)

**Comment by hsaliak** [comment]
@ejona86 I just realize that my earlier comment covers the same issue you raise in your earlier comment and improved in #271 . 
Perhaps thats indication that we need to improve the consistency between paragraph texts and list item texts even further? See attached screenshot.

**Comment by ejona86** [comment]
@hsaliak what "stylistic variation" are you referring to? There is a 1px size difference (16px vs 15px), but it shows up pretty noticeable. Is that it? Font is the same. Font weight I fixed in #271 to match.

**Comment by hsaliak** [comment]
- [ ] Switch all references to http://grpc.io/release to https://grpc.github.io/release @dgquintas

**Comment by ejona86** [comment]
@hsaliak I don't think swapping to https://grpc.github.io/release does any good, because it redirects to http://www.grpc.io/release. So it gives a better _appearance_ but doesn't address the actual issue.

**Comment by ejona86** [comment]
@hsaliak, @dgquintas  Instead of having people curl /release, why don't we just use `{{ site.data.config.grpc_release_branch }}` directly in the markdown?

**Comment by dgquintas** [comment]
@ejona86 that's actually a great idea. Talk about over-engineered solutions...

**Comment by hsaliak** [comment]
@ejona86 thanks for spotting that, i followed the redirects, not what i expected..

**Comment by ejona86** [comment]
* [ ] Remove extraneous indentation in all code snippets. There is very little vertical space, we shouldn't squander it on indentation that applies to all lines in the snippet.
 * [ ] Word-wrap lines.  In general, markdown is supposed to be word-wrapped because it may be read like a txt file. This is purely nice to have, can happen at any time, and has no visible impact on the website.

**Comment by dgquintas** [comment]
- [ ] There are two C# quickstarts: one in `docs/quickstart/csharp.md` and another one at `docs/quickstarts/csharp-quickstart.md` @apolcyn

**Comment by apolcyn** [comment]
@dgquintas sorry missed that https://github.com/grpc/grpc.github.io/pull/288 moves the quickstart that is currently committed.

**Comment by ejona86** [comment]
* [ ] Community page says "You can reach us via... IRC" but doesn't provide the IRC channel information @hsaliak

**Comment by dgquintas** [comment]
@ejona86 it's a test! Shrewd users only :P

**Comment by ejona86** [comment]
* [ ] Contribution guidelines can overlap with header.
![screenshot 2016-08-04 at 4 40 25 pm](https://cloud.githubusercontent.com/assets/2811396/17421888/3a3fc5d0-5a62-11e6-9767-00282c2485de.png)
 * [ ] Contribution guidelines has extraneous fragment on link (contribute/#contribute/index.html)

**Comment by ejona86** [comment]
* [ ] For the final release, double check that Android helloworld points at the right place. It was moved post-pre2 when routeguide was added, so references to it have a high chance of being wrong (luckily, I don't think we have any references).

**Comment by zinuga** [comment]
Fixed community page IRC link

**Comment by hsaliak** [comment]
Removed blog post sign ups.

**Comment by ejona86** [comment]
* [ ] `docs/guides/hello.md` has "This example is also part of Java gRPC's build" which is out-of-date

**Comment by ejona86** [comment]
Calling it done.
